import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from "react";


const defaultRemainingTime = {
  seconds: '00',
  minutes: '00',
  hours: '00',
  days: '00'
}

const CountdownTimer = ({countdownTimestampMs}) => {
  const [remainingTime, setRemainingTime] = useState(defaultRemainingTime);

  useEffect(() => {
      const intervalId = setInterval(() => {
          updateRemainingTime(countdownTimestampMs);
      }, 1000);
      return () => clearInterval(intervalId);
  },[countdownTimestampMs]);

  function updateRemainingTime(countdown) {
      setRemainingTime(getRemainingTimeUntilMsTimestamp(countdown));
  }


}


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Gratis Digital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">
        <h1 className="text-white uppercase font-bold text-2xl md:text-4xl text-center leading-relaxed mb-4">
          Something Awesome is <br/> coming soon
        </h1>
        <p className="text-white text-center">
          Your all-in-one affiliate marketing tracking software track, automate and <br/>optimize your campaigns.
        </p>

        <div className="flex justify-center m-6">
        <div className="h-20 w-16 bg-white rounded mr-4"></div>
        <div className="h-20 w-16 bg-white rounded mr-4"></div>
        <div className="h-20 w-16 bg-white rounded mr-4"></div>
        <div className="h-20 w-16 bg-white rounded"></div>
        </div>

        <form>
        <div className="flex justify-center m-8">
        <input type="text" id="fname" name="fname" placeholder="First Name." className="pr-4 mr-4 bg-bgColor border-b-2 border-gray-500 focus:outline-none placeholder:text-gray-500 text-gray-500"/>
        <input type="text" id="lname" name="lname" placeholder="Last Name." className="mr-4 bg-bgColor border-b-2 border-gray-500 focus:outline-none placeholder:text-gray-500 text-gray-500"/>
        </div>
        <div className="flex justify-center">
        <input type="email" name="lname" placeholder="Enter your email address." className="w-96 mr-4 p-3 rounded-full border-gray-500 focus:outline-none placeholder:text-gray-500 text-gray-500"/>
        <button type="button" className=" relative right-16 text-white bg-btnBg
        uppercase rounded-full px-4 py-1.5  ml-2 text-center inline-flex items-center">
        <Link href="/">
        Join our waiting list.
        </Link>
        </button>
        </div>
        </form>

      </main>

      
      

    </div>
  )
}
